# Generated by Django 3.2.18 on 2023-02-17 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230217_1550'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
